name: repro
on:
  push:
  workflow_dispatch:

jobs:
  via-moon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: moon --version
      - run: ./allowed-to-fail.sh moon run demo:fail-with-random-allowed-to-fail-codes

  direct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./allowed-to-fail.sh ./fail.sh
